/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectPoolRouteImport } from './routes/select-pool'
import { Route as ScanLiveRouteImport } from './routes/scan-live'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsTestIdRouteImport } from './routes/results.$testId'
import { Route as PoolNewRouteImport } from './routes/pool.new'
import { Route as PoolPoolIdRouteImport } from './routes/pool.$poolId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPoolRoute = SelectPoolRouteImport.update({
  id: '/select-pool',
  path: '/select-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLiveRoute = ScanLiveRouteImport.update({
  id: '/scan-live',
  path: '/scan-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsTestIdRoute = ResultsTestIdRouteImport.update({
  id: '/results/$testId',
  path: '/results/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolNewRoute = PoolNewRouteImport.update({
  id: '/pool/new',
  path: '/pool/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolPoolIdRoute = PoolPoolIdRouteImport.update({
  id: '/pool/$poolId',
  path: '/pool/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pools': typeof PoolsRoute
  '/scan': typeof ScanRoute
  '/scan-live': typeof ScanLiveRoute
  '/select-pool': typeof SelectPoolRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/pool/new': typeof PoolNewRoute
  '/results/$testId': typeof ResultsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pools': typeof PoolsRoute
  '/scan': typeof ScanRoute
  '/scan-live': typeof ScanLiveRoute
  '/select-pool': typeof SelectPoolRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/pool/new': typeof PoolNewRoute
  '/results/$testId': typeof ResultsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pools': typeof PoolsRoute
  '/scan': typeof ScanRoute
  '/scan-live': typeof ScanLiveRoute
  '/select-pool': typeof SelectPoolRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/pool/new': typeof PoolNewRoute
  '/results/$testId': typeof ResultsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pools'
    | '/scan'
    | '/scan-live'
    | '/select-pool'
    | '/signup'
    | '/welcome'
    | '/pool/$poolId'
    | '/pool/new'
    | '/results/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pools'
    | '/scan'
    | '/scan-live'
    | '/select-pool'
    | '/signup'
    | '/welcome'
    | '/pool/$poolId'
    | '/pool/new'
    | '/results/$testId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pools'
    | '/scan'
    | '/scan-live'
    | '/select-pool'
    | '/signup'
    | '/welcome'
    | '/pool/$poolId'
    | '/pool/new'
    | '/results/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PoolsRoute: typeof PoolsRoute
  ScanRoute: typeof ScanRoute
  ScanLiveRoute: typeof ScanLiveRoute
  SelectPoolRoute: typeof SelectPoolRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  PoolPoolIdRoute: typeof PoolPoolIdRoute
  PoolNewRoute: typeof PoolNewRoute
  ResultsTestIdRoute: typeof ResultsTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-pool': {
      id: '/select-pool'
      path: '/select-pool'
      fullPath: '/select-pool'
      preLoaderRoute: typeof SelectPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-live': {
      id: '/scan-live'
      path: '/scan-live'
      fullPath: '/scan-live'
      preLoaderRoute: typeof ScanLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$testId': {
      id: '/results/$testId'
      path: '/results/$testId'
      fullPath: '/results/$testId'
      preLoaderRoute: typeof ResultsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/new': {
      id: '/pool/new'
      path: '/pool/new'
      fullPath: '/pool/new'
      preLoaderRoute: typeof PoolNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$poolId': {
      id: '/pool/$poolId'
      path: '/pool/$poolId'
      fullPath: '/pool/$poolId'
      preLoaderRoute: typeof PoolPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PoolsRoute: PoolsRoute,
  ScanRoute: ScanRoute,
  ScanLiveRoute: ScanLiveRoute,
  SelectPoolRoute: SelectPoolRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  PoolPoolIdRoute: PoolPoolIdRoute,
  PoolNewRoute: PoolNewRoute,
  ResultsTestIdRoute: ResultsTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
