/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectStripRouteImport } from './routes/select-strip'
import { Route as SelectPoolRouteImport } from './routes/select-pool'
import { Route as ScanLiveRouteImport } from './routes/scan-live'
import { Route as ScanConfirmRouteImport } from './routes/scan-confirm'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsTestIdRouteImport } from './routes/results.$testId'
import { Route as PoolNewRouteImport } from './routes/pool.new'
import { Route as PoolPoolIdRouteImport } from './routes/pool.$poolId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectStripRoute = SelectStripRouteImport.update({
  id: '/select-strip',
  path: '/select-strip',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPoolRoute = SelectPoolRouteImport.update({
  id: '/select-pool',
  path: '/select-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLiveRoute = ScanLiveRouteImport.update({
  id: '/scan-live',
  path: '/scan-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanConfirmRoute = ScanConfirmRouteImport.update({
  id: '/scan-confirm',
  path: '/scan-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsTestIdRoute = ResultsTestIdRouteImport.update({
  id: '/results/$testId',
  path: '/results/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolNewRoute = PoolNewRouteImport.update({
  id: '/pool/new',
  path: '/pool/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolPoolIdRoute = PoolPoolIdRouteImport.update({
  id: '/pool/$poolId',
  path: '/pool/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pools': typeof PoolsRoute
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/scan-confirm': typeof ScanConfirmRoute
  '/scan-live': typeof ScanLiveRoute
  '/select-pool': typeof SelectPoolRoute
  '/select-strip': typeof SelectStripRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/pool/new': typeof PoolNewRoute
  '/results/$testId': typeof ResultsTestIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pools': typeof PoolsRoute
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/scan-confirm': typeof ScanConfirmRoute
  '/scan-live': typeof ScanLiveRoute
  '/select-pool': typeof SelectPoolRoute
  '/select-strip': typeof SelectStripRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/pool/new': typeof PoolNewRoute
  '/results/$testId': typeof ResultsTestIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pools': typeof PoolsRoute
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/scan-confirm': typeof ScanConfirmRoute
  '/scan-live': typeof ScanLiveRoute
  '/select-pool': typeof SelectPoolRoute
  '/select-strip': typeof SelectStripRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/pool/$poolId': typeof PoolPoolIdRoute
  '/pool/new': typeof PoolNewRoute
  '/results/$testId': typeof ResultsTestIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/login'
    | '/pools'
    | '/pricing'
    | '/scan'
    | '/scan-confirm'
    | '/scan-live'
    | '/select-pool'
    | '/select-strip'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/pool/$poolId'
    | '/pool/new'
    | '/results/$testId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/login'
    | '/pools'
    | '/pricing'
    | '/scan'
    | '/scan-confirm'
    | '/scan-live'
    | '/select-pool'
    | '/select-strip'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/pool/$poolId'
    | '/pool/new'
    | '/results/$testId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/login'
    | '/pools'
    | '/pricing'
    | '/scan'
    | '/scan-confirm'
    | '/scan-live'
    | '/select-pool'
    | '/select-strip'
    | '/settings'
    | '/signup'
    | '/welcome'
    | '/pool/$poolId'
    | '/pool/new'
    | '/results/$testId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PoolsRoute: typeof PoolsRoute
  PricingRoute: typeof PricingRoute
  ScanRoute: typeof ScanRoute
  ScanConfirmRoute: typeof ScanConfirmRoute
  ScanLiveRoute: typeof ScanLiveRoute
  SelectPoolRoute: typeof SelectPoolRoute
  SelectStripRoute: typeof SelectStripRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  PoolPoolIdRoute: typeof PoolPoolIdRoute
  PoolNewRoute: typeof PoolNewRoute
  ResultsTestIdRoute: typeof ResultsTestIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-strip': {
      id: '/select-strip'
      path: '/select-strip'
      fullPath: '/select-strip'
      preLoaderRoute: typeof SelectStripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-pool': {
      id: '/select-pool'
      path: '/select-pool'
      fullPath: '/select-pool'
      preLoaderRoute: typeof SelectPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-live': {
      id: '/scan-live'
      path: '/scan-live'
      fullPath: '/scan-live'
      preLoaderRoute: typeof ScanLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-confirm': {
      id: '/scan-confirm'
      path: '/scan-confirm'
      fullPath: '/scan-confirm'
      preLoaderRoute: typeof ScanConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$testId': {
      id: '/results/$testId'
      path: '/results/$testId'
      fullPath: '/results/$testId'
      preLoaderRoute: typeof ResultsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/new': {
      id: '/pool/new'
      path: '/pool/new'
      fullPath: '/pool/new'
      preLoaderRoute: typeof PoolNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$poolId': {
      id: '/pool/$poolId'
      path: '/pool/$poolId'
      fullPath: '/pool/$poolId'
      preLoaderRoute: typeof PoolPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PoolsRoute: PoolsRoute,
  PricingRoute: PricingRoute,
  ScanRoute: ScanRoute,
  ScanConfirmRoute: ScanConfirmRoute,
  ScanLiveRoute: ScanLiveRoute,
  SelectPoolRoute: SelectPoolRoute,
  SelectStripRoute: SelectStripRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  PoolPoolIdRoute: PoolPoolIdRoute,
  PoolNewRoute: PoolNewRoute,
  ResultsTestIdRoute: ResultsTestIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
